/**
 * Team Form Component
 * Modal form for creating doubles teams
 */

import type {
  Player,
  Team,
  CreateTeamData,
  TeamResponse,
  PlayerListResponse,
} from '../types/player.js';
import { toast } from './toast.js';

export interface TeamFormOptions {
  clubId: string;
  players?: Player[];
  onSuccess?: (team: Team) => void;
  onCancel?: () => void;
}

interface FormErrors {
  player1?: string;
  player2?: string;
}

export class TeamForm {
  private clubId: string;
  private players: Player[] = [];
  private onSuccess?: (team: Team) => void;
  private onCancel?: () => void;
  private overlay: HTMLElement | null = null;
  private isSubmitting = false;
  private isLoadingPlayers = false;
  private errors: FormErrors = {};

  private selectedPlayer1: Player | null = null;
  private selectedPlayer2: Player | null = null;
  private player1Search = '';
  private player2Search = '';

  constructor(options: TeamFormOptions) {
    this.clubId = options.clubId;
    this.players = options.players || [];
    this.onSuccess = options.onSuccess;
    this.onCancel = options.onCancel;

    if (this.players.length === 0) {
      this.fetchPlayers();
    }

    this.render();
  }

  private async fetchPlayers(): Promise<void> {
    this.isLoadingPlayers = true;
    try {
      const response = await fetch(`/api/clubs/${this.clubId}/players`, {
        credentials: 'include',
      });

      if (!response.ok) {
        throw new Error('Failed to fetch players');
      }

      const data: PlayerListResponse = await response.json();
      this.players = data.players || [];
    } catch (error) {
      console.error('Failed to fetch players:', error);
      toast.error('Failed to load players');
    } finally {
      this.isLoadingPlayers = false;
      this.updateDropdowns();
    }
  }

  private render(): void {
    this.overlay = document.createElement('div');
    this.overlay.className = 'modal-overlay';
    this.overlay.innerHTML = this.renderModal();

    document.body.appendChild(this.overlay);

    requestAnimationFrame(() => {
      this.overlay?.classList.add('modal-overlay--visible');
    });

    this.bindEvents();
  }

  private renderModal(): string {
    const autoName = this.getAutoGeneratedName();

    return `
      <div class="modal" style="max-width: 450px;">
        <div class="modal__header">
          <h2 class="modal__title">Create Team</h2>
          <button class="modal__close" aria-label="Close">&times;</button>
        </div>
        <form id="team-form" class="modal__body">
          <div class="form-row">
            <label class="form-label form-label--required" for="team-player1">Player 1</label>
            <div class="searchable-dropdown" id="player1-dropdown">
              <input
                type="text"
                id="team-player1"
                class="searchable-dropdown__input"
                placeholder="Search for a player..."
                value="${this.selectedPlayer1 ? this.escapeHtml(this.selectedPlayer1.name) : ''}"
                autocomplete="off"
              />
              <div class="searchable-dropdown__list" id="player1-list" style="display: none;">
                ${this.renderPlayerOptions(1)}
              </div>
            </div>
            <div class="form-error" id="player1-error"></div>
          </div>

          <div class="form-row">
            <label class="form-label form-label--required" for="team-player2">Player 2</label>
            <div class="searchable-dropdown" id="player2-dropdown">
              <input
                type="text"
                id="team-player2"
                class="searchable-dropdown__input"
                placeholder="Search for a player..."
                value="${this.selectedPlayer2 ? this.escapeHtml(this.selectedPlayer2.name) : ''}"
                autocomplete="off"
              />
              <div class="searchable-dropdown__list" id="player2-list" style="display: none;">
                ${this.renderPlayerOptions(2)}
              </div>
            </div>
            <div class="form-error" id="player2-error"></div>
          </div>

          <div class="form-row">
            <label class="form-label" for="team-name">Team Name</label>
            <input
              type="text"
              id="team-name"
              class="form-input"
              placeholder="${autoName || 'Enter team name or leave blank to auto-generate'}"
              value=""
            />
            <div class="form-hint">Optional. Will be generated from player names if left blank.</div>
          </div>
        </form>
        <div class="modal__footer">
          <button type="button" class="btn btn-outline" id="cancel-btn">Cancel</button>
          <button type="submit" form="team-form" class="btn btn-primary" id="submit-btn">
            <span class="btn-text">Create Team</span>
            <span class="btn-loading" hidden>Creating...</span>
          </button>
        </div>
      </div>
    `;
  }

  private renderPlayerOptions(dropdownNum: 1 | 2): string {
    if (this.isLoadingPlayers) {
      return '<div class="searchable-dropdown__empty">Loading players...</div>';
    }

    const search = dropdownNum === 1 ? this.player1Search : this.player2Search;
    const otherSelected = dropdownNum === 1 ? this.selectedPlayer2 : this.selectedPlayer1;

    let filteredPlayers = this.players;

    if (search) {
      const query = search.toLowerCase();
      filteredPlayers = filteredPlayers.filter(p =>
        p.name.toLowerCase().includes(query)
      );
    }

    if (filteredPlayers.length === 0) {
      return '<div class="searchable-dropdown__empty">No players found</div>';
    }

    return filteredPlayers.map(player => {
      const isDisabled = otherSelected?.id === player.id;
      const isSelected = dropdownNum === 1
        ? this.selectedPlayer1?.id === player.id
        : this.selectedPlayer2?.id === player.id;

      return `
        <div
          class="searchable-dropdown__item ${isSelected ? 'searchable-dropdown__item--selected' : ''} ${isDisabled ? 'searchable-dropdown__item--disabled' : ''}"
          data-player-id="${player.id}"
          data-dropdown="${dropdownNum}"
        >
          ${this.escapeHtml(player.name)}
          ${isDisabled ? ' (already selected)' : ''}
        </div>
      `;
    }).join('');
  }

  private getAutoGeneratedName(): string {
    if (this.selectedPlayer1 && this.selectedPlayer2) {
      const lastName1 = this.selectedPlayer1.name.split(' ').pop() || this.selectedPlayer1.name;
      const lastName2 = this.selectedPlayer2.name.split(' ').pop() || this.selectedPlayer2.name;
      return `${lastName1} / ${lastName2}`;
    }
    return '';
  }

  private bindEvents(): void {
    if (!this.overlay) return;

    // Close button
    const closeBtn = this.overlay.querySelector('.modal__close');
    if (closeBtn) {
      closeBtn.addEventListener('click', () => this.close());
    }

    // Cancel button
    const cancelBtn = this.overlay.querySelector('#cancel-btn');
    if (cancelBtn) {
      cancelBtn.addEventListener('click', () => this.close());
    }

    // Click outside to close
    this.overlay.addEventListener('click', (e) => {
      if (e.target === this.overlay) {
        this.close();
      }
    });

    // Form submit
    const form = this.overlay.querySelector('#team-form') as HTMLFormElement;
    if (form) {
      form.addEventListener('submit', (e) => this.handleSubmit(e));
    }

    // Player 1 dropdown
    const player1Input = this.overlay.querySelector('#team-player1') as HTMLInputElement;
    const player1List = this.overlay.querySelector('#player1-list') as HTMLElement;

    if (player1Input && player1List) {
      player1Input.addEventListener('focus', () => {
        player1List.style.display = 'block';
      });

      player1Input.addEventListener('input', (e) => {
        this.player1Search = (e.target as HTMLInputElement).value;
        this.selectedPlayer1 = null;
        this.updateDropdowns();
      });

      player1Input.addEventListener('blur', () => {
        // Delay to allow click on dropdown item
        setTimeout(() => {
          player1List.style.display = 'none';
          if (this.selectedPlayer1) {
            player1Input.value = this.selectedPlayer1.name;
          }
        }, 200);
      });
    }

    // Player 2 dropdown
    const player2Input = this.overlay.querySelector('#team-player2') as HTMLInputElement;
    const player2List = this.overlay.querySelector('#player2-list') as HTMLElement;

    if (player2Input && player2List) {
      player2Input.addEventListener('focus', () => {
        player2List.style.display = 'block';
      });

      player2Input.addEventListener('input', (e) => {
        this.player2Search = (e.target as HTMLInputElement).value;
        this.selectedPlayer2 = null;
        this.updateDropdowns();
      });

      player2Input.addEventListener('blur', () => {
        setTimeout(() => {
          player2List.style.display = 'none';
          if (this.selectedPlayer2) {
            player2Input.value = this.selectedPlayer2.name;
          }
        }, 200);
      });
    }

    // Dropdown item clicks
    this.bindDropdownItemClicks();

    // ESC key to close
    document.addEventListener('keydown', this.handleKeyDown);
  }

  private bindDropdownItemClicks(): void {
    const items = this.overlay?.querySelectorAll('.searchable-dropdown__item');
    items?.forEach(item => {
      item.addEventListener('mousedown', (e) => {
        e.preventDefault(); // Prevent blur from firing first
        const playerId = item.getAttribute('data-player-id');
        const dropdownNum = parseInt(item.getAttribute('data-dropdown') || '1') as 1 | 2;
        const player = this.players.find(p => p.id === playerId);

        if (player && !item.classList.contains('searchable-dropdown__item--disabled')) {
          if (dropdownNum === 1) {
            this.selectedPlayer1 = player;
            this.player1Search = '';
            const input = this.overlay?.querySelector('#team-player1') as HTMLInputElement;
            if (input) input.value = player.name;
          } else {
            this.selectedPlayer2 = player;
            this.player2Search = '';
            const input = this.overlay?.querySelector('#team-player2') as HTMLInputElement;
            if (input) input.value = player.name;
          }
          this.updateDropdowns();
          this.updateNamePlaceholder();
        }
      });
    });
  }

  private handleKeyDown = (e: KeyboardEvent): void => {
    if (e.key === 'Escape') {
      this.close();
    }
  };

  private async handleSubmit(e: Event): Promise<void> {
    e.preventDefault();

    if (this.isSubmitting) return;

    if (!this.validate()) return;

    this.isSubmitting = true;
    this.setLoading(true);

    try {
      const data = this.getFormData();

      const response = await fetch(`/api/clubs/${this.clubId}/teams`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to create team');
      }

      const result: TeamResponse = await response.json();
      toast.success('Team created successfully');
      this.close();
      this.onSuccess?.(result.team);
    } catch (error) {
      console.error('Failed to create team:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to create team');
    } finally {
      this.isSubmitting = false;
      this.setLoading(false);
    }
  }

  private validate(): boolean {
    this.errors = {};
    let isValid = true;

    if (!this.selectedPlayer1) {
      this.errors.player1 = 'Please select Player 1';
      isValid = false;
    }

    if (!this.selectedPlayer2) {
      this.errors.player2 = 'Please select Player 2';
      isValid = false;
    }

    if (this.selectedPlayer1 && this.selectedPlayer2 &&
        this.selectedPlayer1.id === this.selectedPlayer2.id) {
      this.errors.player2 = 'Player 2 must be different from Player 1';
      isValid = false;
    }

    this.showErrors();
    return isValid;
  }

  private showErrors(): void {
    // Clear previous errors
    this.overlay?.querySelectorAll('.form-error').forEach((el) => {
      el.textContent = '';
    });
    this.overlay?.querySelectorAll('.searchable-dropdown__input').forEach((el) => {
      el.classList.remove('form-input--error');
    });

    if (this.errors.player1) {
      const el = this.overlay?.querySelector('#player1-error');
      const input = this.overlay?.querySelector('#team-player1');
      if (el) el.textContent = this.errors.player1;
      input?.classList.add('form-input--error');
    }

    if (this.errors.player2) {
      const el = this.overlay?.querySelector('#player2-error');
      const input = this.overlay?.querySelector('#team-player2');
      if (el) el.textContent = this.errors.player2;
      input?.classList.add('form-input--error');
    }
  }

  private getFormData(): CreateTeamData {
    const nameInput = this.overlay?.querySelector('#team-name') as HTMLInputElement;
    const name = nameInput.value.trim() || this.getAutoGeneratedName();

    return {
      player1Id: this.selectedPlayer1!.id,
      player2Id: this.selectedPlayer2!.id,
      name,
    };
  }

  private updateDropdowns(): void {
    const player1List = this.overlay?.querySelector('#player1-list');
    const player2List = this.overlay?.querySelector('#player2-list');

    if (player1List) {
      player1List.innerHTML = this.renderPlayerOptions(1);
    }
    if (player2List) {
      player2List.innerHTML = this.renderPlayerOptions(2);
    }

    this.bindDropdownItemClicks();
  }

  private updateNamePlaceholder(): void {
    const nameInput = this.overlay?.querySelector('#team-name') as HTMLInputElement;
    if (nameInput) {
      const autoName = this.getAutoGeneratedName();
      nameInput.placeholder = autoName || 'Enter team name or leave blank to auto-generate';
    }
  }

  private setLoading(loading: boolean): void {
    const submitBtn = this.overlay?.querySelector('#submit-btn') as HTMLButtonElement;
    const btnText = submitBtn?.querySelector('.btn-text') as HTMLElement;
    const btnLoading = submitBtn?.querySelector('.btn-loading') as HTMLElement;

    if (submitBtn) {
      submitBtn.disabled = loading;
    }
    if (btnText) {
      btnText.hidden = loading;
    }
    if (btnLoading) {
      btnLoading.hidden = !loading;
    }
  }

  close(): void {
    document.removeEventListener('keydown', this.handleKeyDown);

    if (this.overlay) {
      this.overlay.classList.remove('modal-overlay--visible');
      setTimeout(() => {
        this.overlay?.remove();
        this.overlay = null;
        this.onCancel?.();
      }, 200);
    }
  }

  private escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  destroy(): void {
    document.removeEventListener('keydown', this.handleKeyDown);
    this.overlay?.remove();
    this.overlay = null;
  }
}
